name: Build and Test
run-name: Build and Test
on:
  pull_request:
    branches: ["you-named-your-branch-like-this"] #Deprecated workflow, remaining for inspection. 
jobs:
  Test-And-Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fang-mcb-project
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: set up environment
        run: | 
          sudo apt-get install python3 python-is-python3 python3-pip git openocd gcc build-essential libboost-all-dev openocd stlink-tools libgmock-dev libgtest-dev pipenv wget -y
          sudo apt-get remove scons -y
          wget https://developer.arm.com/-/media/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          tar -xf gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2
          mv gcc-arm-none-eabi-10.3-2021.10 ~/
      - name: Set Path
        run: |
          echo "~/gcc-arm-none-eabi-10.3-2021.10/bin" >> $GITHUB_PATH
          echo 'export PATH="&{{ github.workspace }}/gcc-arm-none-eabi-10.3-2021.10/bin:$HOME/.local/bin:$PATH:$PATH"' >> ~/.bashrc
      - name: Python Version Install
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.12'
      - name: Pipenv Initialize
        run: |
          pipenv install --python 3.8.12
      - run: pipenv run pip install -U SCons
      - name: build
        run: |
          export PATH="/home/runner/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH"
          pipenv run pip install -r requirements.txt
          pipenv run scons build
      - name: test
        run: |
          export PATH="/home/runner/gcc-arm-none-eabi-10.3-2021.10/bin:$PATH" # Github sets path between steps
          pipenv run scons run-tests
          

      
