name: Docker Build and Test
run-name: Build and Test
on:
  pull_request:
    branches: 
      - "main"
      - 'release/**'
jobs:
  Test-And-Build-Docker:
    strategy:
      matrix:
        type: [build, run-tests]
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/fang-robotics-acc/fang-robotics-mcb/fang-mcb:v5.0.0
      options: --user root
    steps:   
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: |
          git config --global --add safe.directory .
          git config --global --add safe.directory /__w/fang-robotics-mcb/fang-robotics-mcb
          git submodule update --init taproot-scripts
          git submodule update --init --recursive fang-mcb-project
      - name: Restore cache
        uses: actions/cache/save@v4
        id: restore-cache
        with:
          path: fang-mcb-project/build
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Build
        run: |
          cd fang-mcb-project
          scons profile=fast -j 4 ${{matrix.type}} #4 is stanard runner core count
      - name: Update cache
        uses: actions/cache/save@v4
        id: cache
        with:
          path: fang-mcb-project/build
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
