name: Docker Build and Test
run-name: Build and Test
on: [push]
jobs:
  Test-And-Build-Docker:
    runs-on: ubuntu-latest
    container:
      image: docker.io/aruw/mcb-dev:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build
        run: |
          cd fang-mcb-project
          pipenv run scons build
